// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf.converter;

import br.com.tecsoluction.sac.jsf.converter.EmpresaConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmpresaConverter_Roo_Configurable {
    
    declare @type: EmpresaConverter: @Configurable;
    
}
