// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf.converter;

import br.com.tecsoluction.sac.jsf.converter.FormaPagamentoConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FormaPagamentoConverter_Roo_Configurable {
    
    declare @type: FormaPagamentoConverter: @Configurable;
    
}
