// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac;

import br.com.tecsoluction.sac.Imposto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Imposto_Roo_Configurable {
    
    declare @type: Imposto: @Configurable;
    
}
