// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac;

import br.com.tecsoluction.sac.NotaFiscal;

privileged aspect NotaFiscal_Roo_JavaBean {
    
    public String NotaFiscal.getNumero() {
        return this.numero;
    }
    
    public void NotaFiscal.setNumero(String numero) {
        this.numero = numero;
    }
    
}
