// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf;

import br.com.tecsoluction.sac.jsf.PagamentoBean;
import java.io.Serializable;

privileged aspect PagamentoBean_Roo_Serializable {
    
    declare parents: PagamentoBean implements Serializable;
    
    private static final long PagamentoBean.serialVersionUID = 1L;
    
}
