// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf;

import br.com.tecsoluction.sac.jsf.PedidoCompraBean;
import java.io.Serializable;

privileged aspect PedidoCompraBean_Roo_Serializable {
    
    declare parents: PedidoCompraBean implements Serializable;
    
    private static final long PedidoCompraBean.serialVersionUID = 1L;
    
}
