// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf;

import br.com.tecsoluction.sac.jsf.ProdutoBean;
import java.io.Serializable;

privileged aspect ProdutoBean_Roo_Serializable {
    
    declare parents: ProdutoBean implements Serializable;
    
    private static final long ProdutoBean.serialVersionUID = 1L;
    
}
