// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.tecsoluction.sac.jsf;

import br.com.tecsoluction.sac.jsf.RecebimentoBean;
import java.io.Serializable;

privileged aspect RecebimentoBean_Roo_Serializable {
    
    declare parents: RecebimentoBean implements Serializable;
    
    private static final long RecebimentoBean.serialVersionUID = 1L;
    
}
